python mwpo.py \
  --attn_implementation flash_attention_2 \
  --beta 0.01 \
  --bf16 \
  --dataset_name datasets/ultrafeedback_binarized \
  --dataset_train_split train_prefs \
  --do_train \
  --gradient_checkpointing \
  --gradient_accumulation_steps 16 \
  --learning_rate 0.0000005 \
  --len_lambda 0.01 \
  --len_norm \
  --len_scale 256 \
  --lora_r 256 \
  --lora_alpha 32 \
  --logging_steps 5 \
  --loss_type sigmoid \
  --lr_scheduler_type cosine \
  --max_prompt_length 512 \
  --max_length 1024 \
  --max_steps -1 \
  --model_name_or_path model/mistral-7b-sft-beta \
  --num_train_epochs 1 \
  --output_dir model/mistral-swpo \
  --per_device_train_batch_size 2 \
  --report_to tensorboard \
  --save_strategy epoch \
  --save_total_limit 1 \
  --torch_dtype bfloat16 \
  --use_peft \
  --use_rslora \
  --warmup_ratio 0.1 \
  --weighted \
  --weight_alpha 0.625 \
  --weight_beta 0.375
